### ISSUE TITLE
SKlearn classifiers and FastGradientMethod

### ISSUE THREAD

**Issue by ezraabah** [Trusted-AI/adversarial-robustness-toolbox#1148]
FastGradientMethod doesn't work with sklearn classifiers. Keeps returning

"EstimatorError: FastGradientMethod requires an estimator derived from <class 'art.estimators.estimator.BaseEstimator'> and <class 'art.estimators.estimator.LossGradientsMixin'>, the provided classifier is an instance of <class 'art.estimators.classification.scikitlearn.ScikitlearnRandomForestClassifier'> and is derived from (<class 'art.estimators.classification.scikitlearn.ScikitlearnClassifier'>,)"

Works fine with logistic regression and SV classifier.

![image](https://user-images.githubusercontent.com/55036201/121565561-753caf00-ca14-11eb-847e-8b045d9c8ce3.png)
![image](https://user-images.githubusercontent.com/55036201/121565635-8dacc980-ca14-11eb-8741-5e0f72c532c7.png)

**Comment by beat-buesser** [comment]
Hi @ezraabah Thank you very much for using ART! I cannot see the last lines of the stack trace in your second image. There are probably two things happening, first `KNeighborsClassifier` is not yet supported by `SklearnClassifier` and second even if it would be support it would probably not be compatible with `FastGradientMethod` because it does not allow loss gradients to be calculated.

**Comment by ezraabah** [comment]
![image](https://user-images.githubusercontent.com/55036201/121574539-4592a480-ca1e-11eb-88e6-288f30d8fe8d.png)

**Comment by beat-buesser** [comment]
Thank you very much. This means that `KNeighborsClassifier` is not yet supported by `SklearnClassifier`. Would you be interested to implement the required estimator abstraction?

**Comment by ezraabah** [comment]
I got same response for Random Forest Classifier, AdaBoost Classifier, and Gradient Boosting Classifier. Also, These classifiers work well with SklearnClassifier and can be trained till they are to be used as estimators in the FastGradientMethod arg. They also work well as classifiers in Zeroth Order Optimization attack.

**Comment by ezraabah** [comment]
I am interested in implementing the required/missing estimator abstraction. Could you help me through the process?

**Comment by beat-buesser** [comment]
That's great and we are happy to help you!

I have to make my previous message more precise. `SklearnClassifier` takes a scikit-learn classifier model and checks if `art.estimators.classification.scikitlearn` contains any model-specific abstractions (these usually provide loss gradients required for white-box attacks like `FastGradientMethod`), otherwise it defaults to `ScikitlearnClassifier` which is a generic abstraction that can support all scikit-learn models, but only provides methods `fit` and predict (sufficient for black-box attacks like `ZooAttack`).

The `EstimatorError` that you have observed is raised because a white-box attack has been provided a classifier that only provides black-box access which makes them incompatible. The same is true for Random Forest Classifier, AdaBoost Classifier, and Gradient Boosting Classifier which all only support black-box attacks.

If you would like to attack `KNeighborsClassifier` I would propose to implement the attack of Sitawarin and Wagner (https://arxiv.org/abs/2003.06559) which is specifically designed for k-nearest neighbors classifiers. The attack would be located in `art.attacks.evasion` and implement the `EvasionAttack` base class where method `generate` runs the attack.

Let me know if you have further questions!

**Comment by ezraabah** [comment]
Thanks so much. Its my first adversarial ML project and your reply is resourcesful. As you proposed, I'll try the attack of Sitawarin and Wagner on the classifier.
