### ISSUE TITLE
Intel(R) Extension for Scikit-learn for Scikit-learn estimators from ART

### ISSUE THREAD

**Issue by PetrovKP** [Trusted-AI/adversarial-robustness-toolbox#1200]
Hello,

I ran an example [get_started_scikit_learn.py](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/examples/get_started_scikit_learn.py). And FastGradientMethod worked with the estimator SVC more 1h 45min. 

I tired to use `patch_sklearn` from [Intel(R) Extension for Scikit-learn](https://github.com/intel/scikit-learn-intelex) for speedup example. But I got error:

```
----> 1 classifier = SklearnClassifier(model=model, clip_values=(min_pixel_value, max_pixel_value))

~.../lib/python3.8/site-packages/art/estimators/classification/scikitlearn.py in SklearnClassifier(model, clip_values, preprocessing_defences, postprocessing_defences, preprocessing, use_logits)
     75     """
     76     if model.__class__.__module__.split(".")[0] != "sklearn":
---> 77         raise TypeError("Model is not an sklearn model. Received '%s'" % model.__class__)
     78 
     79     sklearn_name = model.__class__.__name__

TypeError: Model is not an sklearn model. Received '<class 'sklearnex.svm.svc.SVC'>'
```
Hence a few questions:
1. Why are these checks needed?
2. Can these checks be removed? This will speed up many algorithms from Scikit-learn in applications. For example for SVM estimators Intel(R) Extension for Scikit-learn have speedup **up to x1000**. See [Medium blog](https://medium.com/intel-analytics-software/leverage-intel-optimizations-in-scikit-learn-f562cb9d5544)
3. Do you have any big tasks/datasets where using scikit-learn takes a very long time for use ART? It would be interesting to see how much you can speed up these tasks with Intel(R) Extension for Scikit-learn.

**Comment by beat-buesser** [comment]
Hi @PetrovKP Thank you very much for your interest in ART! I think the checks are mainly there because, so far, the estimators have only been tested with `sklearn`, the concern is mainly that for calculating the loss gradients the estimators has to access internal variables of the sklearn model, which don't have to but could be different in variants of `sklearn`.

I like the performance improvements in the Medium blog very much! Would you be interested to remove the check and run some tests with ART's `SklearnClassifier` and `ScikitlearnSVC`? It would be a great feature for the upcoming release 1.8 in September and we would be happy to provide help and support.
