### ISSUE TITLE
Acknowledged contributor (mistakenly?) removed from `AUTHORS` off-PR

### ISSUE THREAD

**Issue by eliegoudout** [Trusted-AI/adversarial-robustness-toolbox#2457]
Dear ART team,

First of all, thanks for your amazing work, I love this repo!
I would like to discuss commit fa891f186ba8a6fd6bb8879b9cf805639fa06cea please, and specifically [this comment](https://github.com/Trusted-AI/adversarial-robustness-toolbox/commit/fa891f186ba8a6fd6bb8879b9cf805639fa06cea#r143462692).

For context, [I recently contributed](https://github.com/Trusted-AI/adversarial-robustness-toolbox/pull/2382) to ART by
1. Identifying bug and debugging _Momentum Iterative Method_-based attacks that were previously silently yield wrong results;
2. Correcting the maths from `FGM` with `norm=1`;
3. Extending `FGM` and `PGD` to all real-values `norm` $\geq 1$.

Throughout the PR edition and the merge process, @beat-buesser was very kind by showing interest, providing quick and very relevant feedbacks as well as giving some help when I needed it. For that, I'm very grateful to him/her.
During my work, @beat-buesser kindly acknowledged my additions by [suggesting that I update the AUTHORS file to incorporate my contribution](https://github.com/Trusted-AI/adversarial-robustness-toolbox/pull/2382#issuecomment-2128144501).

Since I made these contributions on my personal spare time, I followed the syntax of [`AUTHORS`](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/AUTHORS):
```
# Names should be added to this file as:
# - Organization
# - Person <email address>
```
As such, I added my contribution
```
- Élie Goudout <eliegoudout@hotmail.com>
```
and @beat-buesser ended up merging my PR with no further comment.

Imagine how surprised I was when I saw that my name was "quietly" removed from `AUTHORS` in an [off-PR commit](https://github.com/Trusted-AI/adversarial-robustness-toolbox/commit/fa891f186ba8a6fd6bb8879b9cf805639fa06cea).
I sincerely hope that this was a mistake that can be hotfixed for `v1.18.0`, because this is not at all what I expected from such a structured open source project. Needless to say that the many contributions, fixes and projects I had in mind for this repo are completly off the table for the time being, which saddens my a great deal since I was very motivated to work on ART, that I found very very cool...

In advance, thanks for your time and consideration.

All the best!
Élie

**Comment by beat-buesser** [comment]
Dear @eliegoudout

Thank you very much for your message and I can understand your point of view and disappointment. I should have contacted you in advance of the change, but because I had asked you for so many changes to make the tests pass, and the nearing deadline of the upcoming release, etc. I thought I would quickly make this change to align your pull request with the project's practices.  Please apologise for not contacting you ahead of the change.

I will try to explain: We have listed only organisations and companies whose employees made contributions during their work-time in the AUTHORS file. We have started this file specifically because GitHub does not have an automated mechanism to track the valuable contribution of these organisations by allowing their employees to work on open-source projects during their work-time. This is why I proposed to you that you may add the name of your employer, because I assumed you had developed the pull request during work-time. I should have asked you if this a work-time contribution before the suggestion. We had decided against listing every contributing person in this file because their list would be much longer and difficult to track accurately, and most importantly because Github automatically tracks contributors/persons that have created commits that got merged into the branch `main` [(contributors).](https://github.com/Trusted-AI/adversarial-robustness-toolbox/graphs/contributors). We currently have 98 contributing user accounts ordered by the number of their contributions and not even the names of the core contributors are listed in the AUTHORS file.

I hope you can understand this practise and that we would like to continue with it. I also hope that you will still think again about continuing working on ART, you made really amazing contributions, but I can also understand if you decide against it.

Best wishes,

Beat

**Comment by eliegoudout** [comment]
Thank you for your honest answer @beat-buesser 👍
