### ISSUE TITLE
AttributeError: 'DecisionTreeClassifier' object has no attribute 'get_trees'  in  RobustnessVerificationTreeModelsCliqueMethod

### ISSUE THREAD

**Issue by ashishcse0031** [Trusted-AI/adversarial-robustness-toolbox#502]
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from art.metrics import RobustnessVerificationTreeModelsCliqueMethod
from art.utils import load_mnist

import warnings
warnings.filterwarnings('ignore')

def get_data(num_classes):
    x_train, y_train = load_iris(return_X_y=True)
    x_train = x_train[y_train < num_classes][:, [0, 1]]
    y_train = y_train[y_train < num_classes]
    x_train[:, 0][y_train == 0] *= 2
    x_train[:, 1][y_train == 2] *= 2
    x_train[:, 0][y_train == 0] -= 3
    x_train[:, 1][y_train == 2] -= 2
    
    x_train[:, 0] = (x_train[:, 0] - 4) / (9 - 4)
    x_train[:, 1] = (x_train[:, 1] - 1) / (6 - 1)
    
    return x_train, y_train

x, y = get_data(2)

model = DecisionTreeClassifier()
model.fit(X=x, y=y)

rbtc = RobustnessVerificationTreeModelsCliqueMethod(model)
result = rbtc.verify(x = x, y = y, eps_init = 0.1, norm = 2, nb_search_steps = 10, max_clique = 2, max_level = 2)

print(result)

**Comment by beat-buesser** [comment]
Hi @ashishcse0031 Thank you very much for using ART! This result is expected because your script is providing an `sklearn` model to `art.metrics.RobustnessVerificationTreeModelsCliqueMethod` where it is expecting an ART estimator from `art.estimators.classification`. `RobustnessVerificationTreeModelsCliqueMethod` in ART also only works for the tree ensemble classifiers.
