### ISSUE TITLE
Can't find an example for using Adversarial Patch!

### ISSUE THREAD

**Issue by weiyikang** [Trusted-AI/adversarial-robustness-toolbox#553]
**Is your feature request related to a problem? Please describe.**
The interface of Adversarial Patch in art.attacks.evasion is hard to use, I can't use the interface guided by the official document. 

**Describe the solution you'd like**
Can I find an example from somewhere?

**Describe alternatives you've considered**
Given an example for using Adversarial Patch.

**Additional context**
The official document may be confusion for using Adversarial Patch:
![image](https://user-images.githubusercontent.com/15953968/90221745-58a80880-de3d-11ea-95e3-22d628f4c91d.png)

**Comment by beat-buesser** [comment]
Hi @weiyikang Why do you think it is confusing?

**Comment by DavidN-EmbedIntel** [comment]
@weiyikang there's an example here if it helps
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/adversarial_patch/attack_adversarial_patch_TensorFlowV2.ipynb
that is I think adapted from the original demo in `cleverhans`
https://github.com/tensorflow/cleverhans/pull/355/files

note that it can be pretty computationally expensive to train a good patch

if you just want to test it, consider copying the patch directly from the Papernot paper (e.g. a screenshot), loading that copy with `PIL` and using the `apply` method of the `art` patch attack instead of generating your own
