### ISSUE TITLE
loss function in carlini.py

### ISSUE THREAD

**Issue by jinglin80** [Trusted-AI/adversarial-robustness-toolbox#627]
On line 153-155 of carlini.py (https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/65b4a1f0c50022fdca7a0e2dc61e0106c3ee9547/art/attacks/evasion/carlini.py), the z_other is defined as follows.

z_other = np.max(
            z_predicted * (1 - target) + (np.min(z_predicted, axis=1) - 1)[:, np.newaxis] * target, axis=1,
        )
However, based on the paper (https://arxiv.org/abs/1608.04644), z_other = np.max( z_predicted * (1 - target), axis=1)
May I know why there is additional term, (np.min(z_predicted, axis=1) - 1)[:, np.newaxis] * target, and is this term always non-positive?

Thank you in advancing

**Comment by mathsinn** [comment]
@jinglin80 Consider the following example:
```
target = np.array([[1, 0, 0]])
z_predicted = np.array([[-1., -2., -3.]])
```
Here we'd expect `z_other` to be `[-2.]` after the assignment. Without the additional term `(np.min(z_predicted, axis=1) - 1)[:, np.newaxis] * target`, however, it would be `[0.]`.

The term can be positive, e.g. consider the above example with `z_predicted = np.array([[5., 4., 3.]])`, however, by construction `z_other` will be `[4.]` in that case as it should be, so that isn't a problem.
