### ISSUE TITLE
Attacked image generated to fool tesseract not working 

### ISSUE THREAD

**Issue by aqsaimtiaz** [Trusted-AI/adversarial-robustness-toolbox#715]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - OS - windows
 - Python version - 3.2
 - ART version or commit number
 - TensorFlow / Keras / PyTorch / MXNet version

Hello,
I am using the classifier_blackbox_tesseract notebook available in the toolbox. I am trying to generate a text adversary. The Tessearct output msg print the "assent" while the image is being transformed to "dissent". and the tessearct output the same. but when i use the image produced from the attack to online OCR or even in my tessearct implement, it reads "dissent" not "assent". Seems like the image is not attacked properly. can i have the reason for this. i am trying to generate the text adversaries but those images are failing in online OCR and the implementation link mentioned. 

https://nanonets.com/blog/ocr-with-tesseract/#:~:text=Tesseract%20library%20is%20shipped%20with,we%20will%20use%20Tesseract's%20API.

**Comment by mathsinn** [comment]
Hi @aqsaimtiaz , thank you for sharing this observation. I don't think this is a bug but actually the expected behaviour: if you create an adversarial example on a specific version of Tesseract, it may not transfer to other versions or different OCR systems. If you want to create adversarial examples for those, you should try applying the HopSkipJump attack directly to them.

**Comment by aqsaimtiaz** [comment]
Hello,

Great. Highly appreciate your response. Thanks for sharing this
information. Let ne try this.

Thanks,
BR,
Aqsa imtiaz
